server:
  port: 8001
spring:
  datasource:
    url: jdbc:mysql://101.33.210.186:3306/frogman_blog?serverTimezone=GMT%2B8&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
  main:
    allow-circular-references: true
  redis:
    host: 101.33.210.186
    port: 6324
    password: 123456
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
files:
  upload:
    path: /Users/allenshen/Desktop/workSpace/FilesStore/

oss:
  accessKey: rmtUUKSy2lNteTMxwCcoi-dApWyQFxgs3H-nWyMa
  secretKey: 8aE4C9fxnJwPeLaVLHq1OJsQQxUSTtK8Re-7Aq5B
  bucket: frogmanblog
  urlPrefix: http://rkb5txjtr.hn-bkt.clouddn.com/
