server:
  port: 8989
spring:
  datasource:
    url: #你的数据库url
    driver-class-name: com.mysql.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
  main:
    allow-circular-references: true
  redis:
    host: 101.33.210.186
    port: 6324
    password: 123456
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
#  七牛云oss配置
oss:
  accessKey: #oss AK
  secretKey: #oss SK
  bucket: # bucket
  urlPrefix: # url前缀
